### ISSUE TITLE
Bot script newbie question

### ISSUE THREAD

**Issue by cstan11** [jvarness/hubot-lunchtime#11]
Hi

Being a newbie to hubot script. I managed to do npm install as per the readme, and added hubot-yelp to the external script list. I can see "lunchtime" has been listed under the hubot help (bot's response). However the command itself "lunchtime" is not responding. 

I am sure I am missing a step because I am not sure where to add in the config for HUBOT_YELP_CONSUMER_KEY. Am I suppose to clone this script under the hubot/script folder?

**Comment by cstan11** [comment]
don't worry about it. I am a newbie :)

**Comment by jvarness** [comment]
Hey @cstan11, thanks for using hubot-yelp!

Did you find the information that you needed?

**Comment by cstan11** [comment]
Yes I did. Thanks for the follow up :+1:
