### ISSUE TITLE
"hubot lunchtime" should be a default command

### ISSUE THREAD

**Issue by jvarness** [jvarness/hubot-lunchtime#2]
The user should be able to use `hubot lunchtime` without any other params.

**Comment by jvarness** [comment]
Also Peter says the docs are bad.

**Comment by pcarn** [comment]
lol sorry. should be easy fixes for all.

**Comment by jvarness** [comment]
Lol no worries my man. I didn't have anyone to review it.

**Comment by jvarness** [comment]
https://github.com/jvarness/hubot-yelp/tree/v0.1.1 fixes this
